# Generated by Django 3.2.3 on 2021-05-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
